name: Build App Module

on: workflow_call

jobs:
  build-modular:
    runs-on: ubuntu-latest
    container: python:slim
    defaults:
      run:
        working-directory: backend
        shell: bash
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3.1.0
      - name: Create virtual environment
        run: python -m venv virtualenv
      - name: Install app requirements
        run: |
          source virtualenv/bin/activate
          apt update
          apt install gcc -y
          pip install --no-cache-dir -r ./requirements.txt
      - name: Upload build
        uses: actions/upload-artifact@v3.1.0
        with:
          name: api-app
          path: ./backend